Router.configure
  layoutTemplate: 'mainLayout'
  notFoundTemplate: 'notFound'
  loadingTemplate: 'loading'

Router.route '/admin',
  name: 'admin',
  controller: 'Admin.HomeController'
Router.route '/admin/users',
  name: 'adminUsers',
  controller: 'Admin.UsersController'
Router.route '/admin/tracks',
  name: 'adminTracks',
  controller: 'Admin.TracksController'
Router.route '/admin/seasons',
  name: 'adminSeasons',
  controller: 'Admin.SeasonsController'
Router.route '/admin/season/:sid',
  name: 'adminSeason',
  controller: 'Admin.SeasonController'
Router.route '/admin/series',
  name: 'adminSeries',
  controller: 'Admin.SeriesController'
Router.route '/admin/series/:id/edit',
  name: 'adminSeriesEdit',
  controller: 'Admin.SeriesEditController'
Router.route '/admin/teams',
  name: 'adminTeams',
  controller: 'Admin.TeamsController'
Router.route '/admin/player-series',
  name: 'adminPlayerSeries',
  controller: 'Admin.PlayerSeriesController'

Router.route '/',
  name: 'home',
  controller: 'HomeController'
Router.route '/teams',
  name: 'teams',
  controller: 'TeamsController'
Router.route '/:tid/seasons/:sid',
  name: 'seasons',
  controller: 'SeasonsController'
Router.route '/:tid/series/:sid',
  name: 'series',
  controller: 'SeriesController'
Router.route '/:tid/my-series/:sid',
  name: 'mySeries',
  controller: 'MySeriesController'
Router.route '/:tid/players',
  name: 'players',
  controller: 'PlayersController'

Router.route '/:tid/player/:nickname/tracks',
  name: 'playerTracks',
  controller: 'PlayerTracksController'
